name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  dast:
    name: OWASP ZAP DAST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Staging Stack
        run: cd infra && docker-compose up -d
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:8080/health'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

  deploy-backend:
    name: Deploy to NIC Cloud / Fly.io
    needs: dast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy Go API
        run: cd backend && flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-frontend:
    name: Deploy to Vercel
    needs: dast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: ./
